=== AMWA-TV/is-10/APIs/schemas/register_client_request.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Register Client Request",
  "description": "Object defining client registration request",
  "type": "object",
  "properties": {
    "redirect_uris": {
      "description": "Array of redirection URI strings for use in redirect-based flows such as the authorization code and implicit flows",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "token_endpoint_auth_method": {
      "description": "String indicator of the requested authentication method for the token endpoint",
      "type": "string",
      "enum": ["client_secret_post", "client_secret_basic", "none"]
    },
    "grant_types": {
      "description": "Array of OAuth 2.0 grant type strings that the client can use at the token endpoint",
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["authorization_code", "implicit", "password", "client_credentials", "refresh_token", "urn:ietf:params:oauth:grant-type:jwt-bearer" ]
      },
      "default": [ "authorization_code" ]
    },
    "response_types": {
      "description": "Array of the OAuth 2.0 response type strings that the client can use at the authorization endpoint",
      "type": "array",
      "items": {
        "type": "string",
        "enum": [ "code", "token" ]
      },
      "default": [ "code" ]
    },
    "client_name": {
      "description": "Human-readable string name of the client to be presented to the end-user during authorization",
      "type": "string"
    },
    "client_uri": {
      "description": "URL string of a web page providing information about the client",
      "type": "string"
    },
    "logo_uri": {
      "description": "URL string that references a logo for the client",
      "type": "string"
    },
    "scope": {
      "description": "String containing a space-separated list of scope values",
      "type": "string"
    },
    "contacts": {
      "description": "Array of strings representing ways to contact people responsible for this client, typically email addresses",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "tos_uri": {
      "description": "URL string that points to a human-readable terms of service document for the client",
      "type": "string"
    },
    "policy_uri": {
      "description": "URL string that points to a human-readable privacy policy document",
      "type": "string"
    },
    "jwks_uri": {
      "description": "URL string referencing the client's JSON Web Key (JWK) Set document, which contains the client's public keys",
      "type": "string"
    },
    "jwks": {
      "description": "Client's JSON Web Key Set document value, which contains the client's public keys",
      "type": "string"
    },
    "software_id": {
      "description": "A unique identifier string (e.g. a UUID) assigned by the client developer or software publisher",
      "type": "string"
    },
    "software_version": {
      "description": "A version identifier string for the client software identified by 'software_id'",
      "type": "string"
    }
  },
  "required": ["redirect_uris", "client_name" ]
}

=== AMWA-TV/is-10/examples/register-authorization-code-grant-client-post-request.json
{
  "client_name": "My Example Client",
  "grant_types": ["authorization_code", "refresh_token"],
  "redirect_uris": [
    "https://client.example.org/callback",
    "https://client.example.org/callback2"
  ],
  "response_types": ["code"],
  "scope": "query connection",
  "token_endpoint_auth_method": "client_secret_basic"
}
